{"uid":"bacf46bd133c5b58","name":"Validate Council Output -- @1.10 Testing : ChelmsfordCityCouncil","fullName":"Test each council output matches expected results in /outputs: Validate Council Output","historyId":"62e27e72c1bfb789c6c8d04a24090df5","time":{"start":1677309857214,"stop":1677309857264,"duration":50},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f341a664be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"uk_bin_collection/tests/features/steps/validate_council.py\", line 34, in step_impl\n    context.parse_result = collect_data.main(args)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py\", line 67, in main\n    return client_code(\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py\", line 23, in client_code\n    return get_bin_data_class.template_method(address_url, **kwargs)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py\", line 56, in template_method\n    page = self.get_data(address_url)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py\", line 84, in get_data\n    full_page = requests.get(url, headers, verify=False)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f341a664be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"uk_bin_collection/tests/features/steps/validate_council.py\", line 34, in step_impl\n    context.parse_result = collect_data.main(args)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py\", line 67, in main\n    return client_code(\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py\", line 23, in client_code\n    return get_bin_data_class.template_method(address_url, **kwargs)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py\", line 56, in template_method\n    page = self.get_data(address_url)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py\", line 84, in get_data\n    full_page = requests.get(url, headers, verify=False)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n","steps":[{"name":"Given the council: \"ChelmsfordCityCouncil\"","time":{"start":1677309857215,"stop":1677309857215,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When we scrape the data from \"ChelmsfordCityCouncil\"","time":{"start":1677309857215,"stop":1677309857263,"duration":48},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f341a664be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"uk_bin_collection/tests/features/steps/validate_council.py\", line 34, in step_impl\n    context.parse_result = collect_data.main(args)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py\", line 67, in main\n    return client_code(\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py\", line 23, in client_code\n    return get_bin_data_class.template_method(address_url, **kwargs)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py\", line 56, in template_method\n    page = self.get_data(address_url)\n  File \"/home/runner/work/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py\", line 84, in get_data\n    full_page = requests.get(url, headers, verify=False)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/uk-bin-collection-EwS6Gn8s-py3.8/lib/python3.8/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"Then the result is valid json","time":{"start":1677309857264,"stop":1677309857264,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"And the output should validate against the schema","time":{"start":1677309857264,"stop":1677309857264,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":4,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Test each council output matches expected results in /outputs"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"council","value":"ChelmsfordCityCouncil"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":12,"skipped":0,"passed":0,"unknown":0,"total":12},"items":[{"uid":"9b18d23b4a3e05a5","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/506//#testresult/9b18d23b4a3e05a5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc46d07a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677309905263,"stop":1677309905353,"duration":90}},{"uid":"81d9e4524abd20aa","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/505//#testresult/81d9e4524abd20aa","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3519f1a8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677308541441,"stop":1677308541531,"duration":90}},{"uid":"dc7472bebeeaeb78","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/504//#testresult/dc7472bebeeaeb78","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0b53b3b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677308246827,"stop":1677308246903,"duration":76}},{"uid":"99e3888c55f76605","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/502//#testresult/99e3888c55f76605","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf373e3160>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677213512571,"stop":1677213512754,"duration":183}},{"uid":"c93ba93c9b25ca81","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/501//#testresult/c93ba93c9b25ca81","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9ee60e3790>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677203099621,"stop":1677203099670,"duration":49}},{"uid":"cc145f8106415662","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/499//#testresult/cc145f8106415662","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91d7a441c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677192155561,"stop":1677192155645,"duration":84}},{"uid":"3747c3d8d6a7320b","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/493//#testresult/3747c3d8d6a7320b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d045c2160>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677044518912,"stop":1677044518978,"duration":66}},{"uid":"3b0119ade9e25549","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/490//#testresult/3b0119ade9e25549","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0409287fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1677030131969,"stop":1677030132047,"duration":78}},{"uid":"703196c8614356cd","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/488//#testresult/703196c8614356cd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f552de623a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1676969791639,"stop":1676969791703,"duration":64}},{"uid":"6a227d5aed02bc1a","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/486//#testresult/6a227d5aed02bc1a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0211006ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1676969210118,"stop":1676969210262,"duration":144}},{"uid":"c97a71e0b7ab38ef","reportUrl":"https://robbrad.github.io/UKBinCollectionData/3.8/484//#testresult/c97a71e0b7ab38ef","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mychelmsford.secure.force.com', port=443): Max retries exceeded with url: /WasteServices/WM_WasteViewProperty?id=XXXXXXXXXXXXXXX&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd1415f5c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n","time":{"start":1676966954626,"stop":1676966954719,"duration":93}}]},"tags":[]},"source":"bacf46bd133c5b58.json","parameterValues":["ChelmsfordCityCouncil"]}